baseURL: https://martasuchanska.eu/
title: Marta Suchańska
theme: martasuchanska.eu
googleAnalytics: UA-83630952-1
defaultContentLanguage: pl
defaultContentLanguageInSubdir: true
languages:
  pl:
    languageCode: pl-pl
    languageName: Polski
    weight: 1
  hu:
    languageCode: hu-hu
    languageName: Magyar
    weight: 2
  en:
    languageCode: en-uk
    weight: 3
    languageName: English
params:
  photo: WWW-Marta-foto2.png
  name: Marta Suchańska
