baseURL: https://martasuchanska.eu/
title: Marta Suchańska
theme: martasuchanska.eu
googleAnalytics: UA-83630952-1
defaultContentLanguage: pl
defaultContentLanguageInSubdir: true
languages:
  pl:
    languageCode: pl-pl
    languageName: Polski
    weight: 1
  hu:
    languageCode: hu-hu
    languageName: Magyar
    weight: 2
  bg:
    languageCode: bg-vg
    languageName: Български
    weight: 3
  en:
    languageCode: en-uk
    languageName: English
    weight: 4
params:
  photo: marta-suchanska.jpg
  name: Marta Suchańska
